-- Copyright (c) 2026, Oracle and/or its affiliates.
-- Builds the sample HR schema and Deep Data Security policies for this demo.
--
-- WARNING: This script drops and recreates the HR schema. Run it only in a new
-- or disposable database as the Autonomous AI Database ADMIN user, after OCI
-- IAM external authentication is configured.
--
-- This script does not configure the database IAM identity provider, IAM
-- groups, OAuth clients, or GenAI tenancy policies. Follow README.md afterward
-- to create the GenAI credential, access synonym, profile, and Agent Team.

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET LINESIZE 200
SET PAGESIZE 100
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

----------------------------------------------------------------------------
-- Replace all values before running.
----------------------------------------------------------------------------
DEFINE APP_DB_USER = db_usr
DEFINE APP_DB_PASSWORD = replace-with-a-strong-password

-- These must exactly match the OCI IAM usernames presented in the user token.
DEFINE MARVIN_USERNAME = marvin
DEFINE EMMA_USERNAME = emma
DEFINE HANNAH_USERNAME = hannah

-- These must exactly match the OCI IAM group names in the user token.
DEFINE OCI_IAM_EMPLOYEE_GROUP = EMPLOYEES
DEFINE OCI_IAM_MANAGER_GROUP = MANAGERS

-- A standard role the Python app can use while Deep Data Security is active.
DEFINE RUNNER_ROLE = HR_SELECT_AI_RUNNER

----------------------------------------------------------------------------
-- 1. Recreate the HR schema and sample data (destructive).
----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP USER hr CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

CREATE USER hr NO AUTHENTICATION
  DEFAULT TABLESPACE data
  QUOTA UNLIMITED ON data;

CREATE TABLE hr.employees (
  employee_id   NUMBER PRIMARY KEY,
  first_name    VARCHAR2(50),
  last_name     VARCHAR2(50),
  job_code      VARCHAR2(10),
  department_id NUMBER,
  ssn           VARCHAR2(20),
  photo         BLOB,
  phone_number  VARCHAR2(30),
  salary        NUMBER(10,2),
  user_name     VARCHAR2(128),
  manager_id    NUMBER
);

INSERT INTO hr.employees VALUES (1, 'Grace', 'Young', 'CEO', NULL, '111-11-1111', NULL, '555-100-0001', 235000, 'grace', NULL);
INSERT INTO hr.employees VALUES (2, 'Marvin', 'Morgan', 'SWE_MGR', 1, '222-22-2222', NULL, '555-100-0002', 175000, '&MARVIN_USERNAME', 1);
INSERT INTO hr.employees VALUES (3, 'Emma', 'Baker', 'SWE2', 1, '333-33-3333', NULL, '555-100-0003', 120000, '&EMMA_USERNAME', 2);
INSERT INTO hr.employees VALUES (4, 'Charlie', 'Davis', 'SWE1', 1, '444-44-4444', NULL, '555-100-0004', 95000, 'charlie', 2);
INSERT INTO hr.employees VALUES (5, 'Dana', 'Lee', 'SWE3', 1, '555-55-5555', NULL, '555-100-0005', 130000, 'dana', 2);
INSERT INTO hr.employees VALUES (6, 'Bob', 'Smith', 'SALES_REP', 2, '666-66-6666', NULL, '555-100-0006', 145000, 'bob', 1);
INSERT INTO hr.employees VALUES (7, 'Fiona', 'Chen', 'HR_REP', 3, '777-77-7777', NULL, '555-100-0007', 92000, 'fiona', 1);
INSERT INTO hr.employees VALUES (8, 'Hannah', 'Mavris', 'HR_REP', 3, '888-88-8888', NULL, '555-100-0008', 98000, '&HANNAH_USERNAME', 1);

CREATE TABLE hr.locations (
  location_id    NUMBER PRIMARY KEY,
  city           VARCHAR2(100) NOT NULL,
  state_province VARCHAR2(100),
  country_id     VARCHAR2(2) NOT NULL
);

CREATE TABLE hr.departments (
  department_id   NUMBER PRIMARY KEY,
  department_name VARCHAR2(100) NOT NULL,
  location_id     NUMBER NOT NULL,
  CONSTRAINT departments_location_fk FOREIGN KEY (location_id)
    REFERENCES hr.locations(location_id)
);

INSERT INTO hr.locations VALUES (100, 'Seattle', 'WA', 'US');
INSERT INTO hr.locations VALUES (110, 'Austin', 'TX', 'US');
INSERT INTO hr.locations VALUES (120, 'New York', 'NY', 'US');
INSERT INTO hr.departments VALUES (1, 'Engineering', 100);
INSERT INTO hr.departments VALUES (2, 'Sales', 110);
INSERT INTO hr.departments VALUES (3, 'Human Resources', 120);

CREATE TABLE hr.performance_notes (
  note_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id          NUMBER NOT NULL,
  manager_id           NUMBER NOT NULL,
  manager_private_note VARCHAR2(4000),
  employee_feedback    VARCHAR2(4000),
  created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT perf_notes_employee_fk FOREIGN KEY (employee_id)
    REFERENCES hr.employees(employee_id),
  CONSTRAINT perf_notes_manager_fk FOREIGN KEY (manager_id)
    REFERENCES hr.employees(employee_id),
  CONSTRAINT perf_notes_has_content_ck CHECK (
    manager_private_note IS NOT NULL OR employee_feedback IS NOT NULL
  )
);

INSERT INTO hr.performance_notes (employee_id, manager_id, manager_private_note, employee_feedback)
VALUES (3, 2, 'Emma is a high-potential employee. Keep private coaching notes here.', 'Good progress this quarter; continue improving status updates.');
INSERT INTO hr.performance_notes (employee_id, manager_id, manager_private_note, employee_feedback)
VALUES (4, 2, 'Charlie needs additional mentoring before the next promotion review.', 'Strong implementation work; focus on proactive project communication.');

----------------------------------------------------------------------------
-- 2. Application schema and required Select AI privileges.
----------------------------------------------------------------------------
DECLARE
  l_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_exists FROM dba_users WHERE username = UPPER('&APP_DB_USER');
  IF l_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER &APP_DB_USER IDENTIFIED BY "&APP_DB_PASSWORD"';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER &APP_DB_USER IDENTIFIED BY "&APP_DB_PASSWORD" ACCOUNT UNLOCK';
  END IF;
END;
/

GRANT CREATE SESSION TO &APP_DB_USER;
GRANT CREATE PROCEDURE TO &APP_DB_USER;
GRANT CREATE END USER SECURITY CONTEXT TO &APP_DB_USER;
GRANT EXECUTE ON DBMS_CLOUD TO &APP_DB_USER;
GRANT EXECUTE ON DBMS_CLOUD_AI TO &APP_DB_USER;
-- The profile/team owner uses the package access-control APIs to share its
-- Select AI objects with the standard role inherited by Deep Sec users.
GRANT EXECUTE ON DBMS_CLOUD_AI_AGENT TO &APP_DB_USER;

----------------------------------------------------------------------------
-- 3. OCI IAM Deep Data Security roles, context, and data grants.
----------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS employee_context_admin;
GRANT UPDATE ANY END USER CONTEXT TO hr;

CREATE OR REPLACE DATA ROLE hrapp_employees
  MAPPED TO 'IAM_OAUTH_GROUP=&OCI_IAM_EMPLOYEE_GROUP';
CREATE OR REPLACE DATA ROLE hrapp_managers
  MAPPED TO 'IAM_OAUTH_GROUP=&OCI_IAM_MANAGER_GROUP';

CREATE ROLE IF NOT EXISTS direct_logon_role;
GRANT CREATE SESSION TO direct_logon_role;
GRANT direct_logon_role TO hrapp_employees;
GRANT direct_logon_role TO hrapp_managers;

CREATE ROLE IF NOT EXISTS &RUNNER_ROLE;
-- Deep Sec end users inherit this standard role through their data role. It
-- lets them set the profile/team and invoke RUN_TEAM in their own session.
GRANT EXECUTE ON DBMS_CLOUD_AI TO &RUNNER_ROLE;
GRANT EXECUTE ON DBMS_CLOUD_AI_AGENT TO &RUNNER_ROLE;
GRANT &RUNNER_ROLE TO hrapp_employees;
GRANT &RUNNER_ROLE TO hrapp_managers;

CREATE OR REPLACE END USER CONTEXT HR.EMP_CTX USING JSON SCHEMA '{
  "type": "object",
  "properties": {
    "ID": {
      "type": "integer",
      "o:onFirstRead": "HR.ctx_pkg.init_user_context"
    }
  }
}';

CREATE OR REPLACE PACKAGE hr.ctx_pkg AS
  PROCEDURE init_user_context;
END;
/

CREATE OR REPLACE PACKAGE BODY hr.ctx_pkg AS
  PROCEDURE init_user_context IS
    l_sql VARCHAR2(4000);
  BEGIN
    l_sql := '
      UPDATE END_USER_CONTEXT t
         SET t.CONTEXT.ID = (
           SELECT e.employee_id
             FROM hr.employees e
            WHERE UPPER(e.user_name) = UPPER(ora_end_user_context.username)
         )
       WHERE owner = ''HR''
         AND name = ''EMP_CTX''';
    EXECUTE IMMEDIATE l_sql;
  END;
END;
/

GRANT EXECUTE ON hr.ctx_pkg TO employee_context_admin;
GRANT employee_context_admin TO hrapp_employees;
GRANT employee_context_admin TO hrapp_managers;

CREATE OR REPLACE DATA GRANT hr.employee_self_access
  AS SELECT (
    employee_id, first_name, last_name, job_code, department_id, manager_id,
    ssn, salary, phone_number, user_name
  )
  ON hr.employees
  WHERE UPPER(user_name) = UPPER(ora_end_user_context.username)
  TO hrapp_employees;

-- Employees can browse non-protected directory fields for everyone. The
-- self grant above remains additive, so each employee can still see their own
-- salary and SSN while those columns stay protected for other employees.
CREATE OR REPLACE DATA GRANT hr.employee_directory_access
  AS SELECT (ALL COLUMNS EXCEPT ssn, salary)
  ON hr.employees
  WHERE 1 = 1
  TO hrapp_employees;

CREATE OR REPLACE DATA GRANT hr.manager_team_access
  AS SELECT (ALL COLUMNS EXCEPT ssn)
  ON hr.employees
  WHERE employee_id IN (
    SELECT employee_id
    FROM hr.employees
    START WITH employee_id = (
      SELECT employee_id
      FROM hr.employees
      WHERE UPPER(user_name) = UPPER(ora_end_user_context.username)
    )
    CONNECT BY PRIOR employee_id = manager_id
  )
  TO hrapp_managers;

CREATE OR REPLACE DATA GRANT hr.employee_context_access
  AS SELECT ON sys.end_user_context
  WHERE owner = 'HR' AND name = 'EMP_CTX'
  TO hrapp_employees, hrapp_managers;

CREATE OR REPLACE DATA GRANT hr.reference_data_access
  AS SELECT ON hr.departments
  TO hrapp_employees, hrapp_managers;
CREATE OR REPLACE DATA GRANT hr.location_data_access
  AS SELECT ON hr.locations
  TO hrapp_employees, hrapp_managers;

CREATE OR REPLACE DATA GRANT hr.performance_notes_manager_access
  AS SELECT ON hr.performance_notes
  WHERE manager_id = ora_end_user_context.hr.emp_ctx.id
  TO hrapp_managers;
CREATE OR REPLACE DATA GRANT hr.performance_notes_employee_access
  AS SELECT (note_id, employee_id, manager_id, employee_feedback, created_at)
  ON hr.performance_notes
  WHERE employee_id = ora_end_user_context.hr.emp_ctx.id
  TO hrapp_employees;

COMMIT;

----------------------------------------------------------------------------
-- 4. Verification.
----------------------------------------------------------------------------
COLUMN user_name FORMAT A45
SELECT employee_id, first_name, last_name, job_code, department_id, user_name
FROM hr.employees
ORDER BY employee_id;

SELECT data_role, mapped_to, enabled_by_default
FROM dba_data_roles
WHERE data_role IN ('HRAPP_EMPLOYEES', 'HRAPP_MANAGERS')
ORDER BY data_role;

SELECT granted_role
FROM dba_role_privs
WHERE grantee IN ('HRAPP_EMPLOYEES', 'HRAPP_MANAGERS')
  AND granted_role = UPPER('&RUNNER_ROLE')
ORDER BY grantee;
