Rem
Rem Copyright (c) 2026, Oracle and/or its affiliates.
Rem
Rem    NAME
Rem      setup.sql - Setup script for
Rem      LangChain Agent Sample HR application
Rem
Rem    DESCRIPTION
Rem      Creates sample employee, manager, and performance-notes tables,
Rem      sample users, data roles, and Deep Data Security grants required
Rem      for the LangChain Agent Sample HR application.
Rem
Rem    NOTES
Rem      Update Azure application identifiers, database credentials,
Rem      users, and tenant details before execution.
Rem
Rem    BEGIN SQL_FILE_METADATA
Rem    SQL_SOURCE_FILE: tkmain_3/tzfd/src/setup.sql
Rem    SQL_SHIPPED_FILE:
Rem    SQL_PHASE:
Rem    SQL_STARTUP_MODE: NORMAL
Rem    SQL_IGNORABLE_ERRORS: NONE
Rem    SQL_CALLING_FILE:
Rem    END SQL_FILE_METADATA
Rem


SET ECHO ON
SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

define passwd=<insert dba password>
define db_usr_passwd=db_usr
define conn_str=<insert connection string>
----------------------------------------------------------------------
-- 1. Update HR employee data, add SSN/test columns, and create the
--    manager and performance-notes tables with sample data
----------------------------------------------------------------------
connect hr/hr@&conn_str
update hr.employees set first_name = 'Hannah', email = 'HANNAH' where first_name = 'Susan' and last_name = 'Mavris';
update hr.employees set first_name = 'Marvin', email = 'MARVIN' where first_name = 'Nancy' and last_name = 'Greenberg';
update hr.employees set first_name = 'Emma', email = 'EMMA' where first_name = 'David' and last_name = 'Austin';

update hr.employees
set last_name = 'Baker'
where first_name = 'Emma';

update hr.employees
set last_name = 'Greenberg'
where first_name = 'Marvin';

commit;

commit;
ALTER TABLE employees ADD ssn VARCHAR2(11);
BEGIN
  FOR rec IN (SELECT employee_id FROM employees) LOOP
   UPDATE employees
   SET ssn = LPAD(DBMS_RANDOM.VALUE(100, 999), 3, '0') || '-' ||
        LPAD(DBMS_RANDOM.VALUE(10, 99), 2, '0') || '-' ||
        LPAD(DBMS_RANDOM.VALUE(1000, 9999), 4, '0')
   WHERE employee_id = rec.employee_id;
  END LOOP;
  COMMIT;
END;
/

-- Update SSN for Marvin, Emma and Hannah to get consistent result
update hr.employees set ssn = '841-11-4324'
  where first_name = 'Emma' and email = 'EMMA';
update hr.employees set ssn = '798-13-9372'
  where first_name = 'Hannah' and email = 'HANNAH';
update hr.employees set ssn = '166-46-3472'
  where first_name = 'Marvin' and email = 'MARVIN';

alter table hr.employees modify (email varchar2(250));

-- Update email ids of the user MARVIN, EMMA and HANNAH
-- Please Note: These EMAIL IDs have been created in Microsoft Entra ID
UPDATE hr.employees
   SET email = '<insert email generated for emma demo user>'
 WHERE UPPER(first_name) = 'EMMA'   AND UPPER(email) = 'EMMA';

UPDATE hr.employees
   SET email = '<insert email generated for marvin demo user>'
 WHERE UPPER(first_name) = 'MARVIN' AND UPPER(email) = 'MARVIN';

UPDATE hr.employees
   SET email = '<insert email generated for hannah demo user>'
 WHERE UPPER(first_name) = 'HANNAH' AND UPPER(email) = 'HANNAH';

ALTER TABLE hr.employees ADD test_tag VARCHAR2(50);

COMMIT;

-- Create managers table
create table hr.managers as select * from hr.employees;

-- Create performance notes table
create table hr.performance_notes (
  note_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id          NUMBER(6) NOT NULL,
  manager_id           NUMBER(6) NOT NULL,
  manager_private_note VARCHAR2(4000),
  employee_feedback    VARCHAR2(4000),
  CONSTRAINT perf_notes_employee_fk
    FOREIGN KEY (employee_id) REFERENCES hr.employees(employee_id),
  CONSTRAINT perf_notes_manager_fk
    FOREIGN KEY (manager_id) REFERENCES hr.employees(employee_id)
);

-- Sample performance notes
INSERT INTO hr.performance_notes (
  employee_id,
  manager_id,
  manager_private_note,
  employee_feedback
) VALUES (
  105,
  103,
  'Emma is a high potential employee; keep private coaching notes here.',
  'Good progress this quarter; continue improving status updates.'
);

INSERT INTO hr.performance_notes (
  employee_id,
  manager_id,
  manager_private_note,
  employee_feedback
) VALUES (
  109,
  108,
  'Needs more stretch assignments before next promotion cycle.',
  'Strong technical work, but should improve cross-team communication.'
);

COMMIT;


----------------------------------------------------------------------
-- 2. Create Connection pool user and Data Role
----------------------------------------------------------------------

connect sys/&passwd@&conn_str as sysdba
-- Create DB user: connection pool user
drop user IF EXISTS db_usr cascade;
create user db_usr identified by &db_usr_passwd;
grant connect to db_usr;
grant CREATE END USER SECURITY CONTEXT to db_usr;

create or replace data role EMPLOYEE_FS_ROLE
mapped to 'AZURE_APP=https://<insert your tenant name>.onmicrosoft.com/<insert midtier app id>:azure_role=EMPLOYEE_ROLE';

create or replace data role MANAGER_FS_ROLE
mapped to 'AZURE_APP=https://<insert your tenant name>.onmicrosoft.com/<insert midtier app id>:azure_role=MANAGER_ROLE';

CREATE OR REPLACE APPLICATION IDENTITY compensation_app
  MAPPED TO 'AZURE_CLIENT_ID=<insert compensation app id>';

CREATE DATA ROLE SALARY_AGENT_FS_ROLE;

GRANT DATA ROLE SALARY_AGENT_FS_ROLE TO compensation_app;

----------------------------------------------------------------------
-- 3. Set identity provider
----------------------------------------------------------------------

connect sys/&passwd@&conn_str as sysdba

ALTER SYSTEM SET IDENTITY_PROVIDER_TYPE=AZURE_AD SCOPE=BOTH;

ALTER SYSTEM SET IDENTITY_PROVIDER_CONFIG =
'{
   "application_id_uri": "https://<insert tenant name>.onmicrosoft.com/<insert db app id>",
   "tenant_id": "<insert tenant id>",
   "app_id": "<insert db app id>"
}' SCOPE=BOTH;


show parameter IDENTITY_PROVIDER_CONFIG

----------------------------------------------------------------------
-- 4. SETUP - Data security policy and data grants
----------------------------------------------------------------------
CREATE OR REPLACE DATA GRANT hr.gnt1 AS
SELECT (ALL COLUMNS EXCEPT ssn, salary) ON hr.employees
WHERE 1=1
TO EMPLOYEE_FS_ROLE;

CREATE OR REPLACE DATA GRANT hr.gnt2 AS
SELECT,
       UPDATE (first_name, phone_number)
ON hr.employees
WHERE UPPER(email) = UPPER(ORA_END_USER_CONTEXT.username)
TO EMPLOYEE_FS_ROLE;

CREATE OR REPLACE DATA GRANT hr.mgr_hierarchy AS
SELECT (ALL COLUMNS EXCEPT ssn) ON hr.employees
WHERE employee_id IN (SELECT employee_id FROM hr.managers START WITH employee_id = (SELECT employee_id FROM hr.managers WHERE UPPER(email) = UPPER(ORA_END_USER_CONTEXT.username))CONNECT BY PRIOR employee_id = manager_id )
TO MANAGER_FS_ROLE;


CREATE OR REPLACE DATA GRANT hr.sal_agent AS
SELECT (ALL COLUMNS EXCEPT employee_id, first_name, last_name, email, phone_number, ssn) ON hr.employees
WHERE 1=1
TO SALARY_AGENT_FS_ROLE;

CREATE OR REPLACE DATA GRANT hr.sal_agent_departments
  AS SELECT
  ON hr.departments
  TO SALARY_AGENT_FS_ROLE;

CREATE OR REPLACE DATA GRANT hr.sal_agent_locations
  AS SELECT
  ON hr.locations
  TO SALARY_AGENT_FS_ROLE;

-- Employees may view their own performance feedback, but not the
-- manager-private note.
CREATE OR REPLACE DATA GRANT hr.perf_notes_emp_grant
  AS SELECT (ALL COLUMNS EXCEPT manager_private_note)
  ON hr.performance_notes
  WHERE employee_id = (
    SELECT e.employee_id
    FROM hr.employees e
    WHERE UPPER(e.email) = UPPER(ORA_END_USER_CONTEXT.username)
  )
  TO EMPLOYEE_FS_ROLE;

-- Managers may view and maintain performance notes for their direct reports.
CREATE OR REPLACE DATA GRANT hr.perf_notes_mgr_grant
  AS SELECT,
     INSERT (
       employee_id,
       manager_id,
       manager_private_note,
       employee_feedback
     ),
     UPDATE (manager_private_note, employee_feedback),
     DELETE
  ON hr.performance_notes
  WHERE manager_id = (
    SELECT m.employee_id
    FROM hr.employees m
    WHERE UPPER(m.email) = UPPER(ORA_END_USER_CONTEXT.username)
  )
  AND employee_id IN (
    SELECT e.employee_id
    FROM hr.employees e
    WHERE e.manager_id = (
      SELECT m.employee_id
      FROM hr.employees m
      WHERE UPPER(m.email) = UPPER(ORA_END_USER_CONTEXT.username)
    )
  )
  TO MANAGER_FS_ROLE;
