#!/bin/bash
# Verify the direct OCI IAM-to-ADB GenAI baseline before creating MCP resources.

set -euo pipefail

GREEN='\033[0;32m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ENV_FILE="${SCRIPT_DIR}/.deep-sec-mcp.env"

usage() {
  cat <<'EOF'
Usage: ./01_verify_genai_baseline.sh

Read-only prerequisite verification for the Deep Security GenAI Demo lab.

Before running this script:
  1. Complete deep-sec-gen-ai-demo against the same ADB.
  2. Start its local service in another terminal:
       ../deep-sec-gen-ai-demo/09_start_identity_service.sh
  3. Obtain a current OCI IAM database token for the user being tested.

This script runs the GenAI identity proof and HR.EMPLOYEES audit report. It
does not create or modify MCP, ADB, IAM, or audit resources.
EOF
}

if [ "${1:-}" = '-h' ] || [ "${1:-}" = '--help' ]; then
  usage
  exit 0
fi

if [ ! -f "$ENV_FILE" ]; then
  echo -e "${RED}ERROR: .deep-sec-mcp.env not found. Run ./00_configure_lab_env.sh first.${NC}" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

for script in 10_verify_identity_service.sh 07_show_hr_employees_audit_trail.sh; do
  if [ ! -x "${GENAI_LAB_DIR:-}/${script}" ]; then
    echo -e "${RED}ERROR: ${GENAI_LAB_DIR:-<unset>}/${script} is missing or not executable.${NC}" >&2
    exit 1
  fi
done

echo
echo -e "${GREEN}============================================================================${NC}"
echo -e "${GREEN}      Verify Deep Security GenAI Baseline Before MCP Setup                  ${NC}"
echo -e "${GREEN}============================================================================${NC}"
echo -e "${CYAN}GenAI lab: ${GENAI_LAB_DIR}${NC}"
echo -e "${CYAN}ADB OCID : ${ADB_OCID}${NC}"
echo
echo 'Running the direct OCI IAM-to-ADB identity proof. A current token and the local GenAI service are required.'
"${GENAI_LAB_DIR}/10_verify_identity_service.sh"

echo
echo 'Reading the latest HR.EMPLOYEES audit events. This is read-only.'
"${GENAI_LAB_DIR}/07_show_hr_employees_audit_trail.sh"

umask 077
cat > "${GENAI_BASELINE_FILE}" <<EOF
# Generated by 01_verify_genai_baseline.sh after read-only checks passed.
export GENAI_BASELINE_VERIFIED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
export GENAI_BASELINE_ADB_OCID="${ADB_OCID}"
export GENAI_BASELINE_LAB_DIR="${GENAI_LAB_DIR}"
EOF

echo
echo -e "${GREEN}GenAI baseline verification passed.${NC}"
echo "Evidence file: ${GENAI_BASELINE_FILE}"
echo 'Next: run ./discover_mcp_inputs.sh. MCP identity propagation remains unproven until its dedicated MCP-to-ADB test is completed.'
