#!/usr/bin/env bash
# Shared, non-resource-mutating helpers for deep-sec-gen-ai-demo.

if [[ -n "${DEEP_SEC_GEN_AI_COMMON_SH_LOADED:-}" ]]; then
  return 0
fi
DEEP_SEC_GEN_AI_COMMON_SH_LOADED=1

LAB_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
readonly LAB_ROOT
readonly LAB_STATE_DIR="${LAB_STATE_DIR:-${LAB_ROOT}/.lab}"
readonly LEGACY_LAB_ROOT="${LAB_ROOT}/../adb-oci-iam"
export LEGACY_LAB_ROOT

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

info() {
  printf '%s\n' "$*"
}

require_command() {
  local command_name=$1
  command -v "$command_name" >/dev/null 2>&1 || die "Required command not found: ${command_name}"
}

sql_client() {
  if command -v sql >/dev/null 2>&1; then
    printf 'sql\n'
  elif command -v sqlplus >/dev/null 2>&1; then
    printf 'sqlplus\n'
  else
    return 1
  fi
}

run_legacy_script() {
  local script_name=$1
  shift
  local script_path="${LEGACY_LAB_ROOT}/${script_name}"
  test -f "$script_path" || die "Legacy script is missing: ${script_path}"

  if [[ "${LAB_DRY_RUN:-0}" == "1" ]]; then
    printf 'DRY RUN:'
    printf ' %q' bash "$script_path"
    if [[ $# -gt 0 ]]; then
      printf ' %q' "$@"
    fi
    printf '\n'
    return 0
  fi

  bash "$script_path" "$@"
}

load_legacy_environment() {
  local attachment_file="${LAB_STATE_DIR}/attached-adb.env"
  local environment_file="${LEGACY_ENV_FILE:-}"
  if [[ "${LAB_DRY_RUN:-0}" == "1" ]]; then
    info "DRY RUN: would load the attached or default adb-oci-iam environment"
    return 0
  fi

  if [[ -z "$environment_file" && -f "$attachment_file" ]]; then
    # shellcheck disable=SC1090 # Written only by attach-adb-oci-iam.sh.
    source "$attachment_file"
    environment_file="${LEGACY_ENV_FILE:-}"
  fi
  environment_file="${environment_file:-${LEGACY_LAB_ROOT}/.adb-oci-iam.env}"
  test -f "$environment_file" || die "Legacy environment file is missing: ${environment_file}. Run './bin/labctl identity configure' first."
  # shellcheck disable=SC1090 # File is generated by the known legacy setup script.
  source "$environment_file"
}
