#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENTRA_LAB_ENV="${ENTRA_LAB_ENV:-${SCRIPT_DIR}/../entra-id-data-grants/.entra-id-data-grants.env}"

if [ -f "$ENTRA_LAB_ENV" ]; then
  # shellcheck disable=SC1090
  source "$ENTRA_LAB_ENV"
fi

: "${PDB_NAME:?PDB_NAME is required}"
DB_SID="${DB_SID:-FREE}"
export ORACLE_SID="$DB_SID"

echo "Cleaning up Web HR App database objects in PDB ${PDB_NAME}"
echo
echo "This script will attempt to disable/drop:"
echo "  WEB_HR_APP_EMPLOYEE_AUDIT audit policy"
echo "  SYS.WEB_HR_DISABLE_SALARY_UPDATES"
echo "  SYS.WEB_HR_ENABLE_SALARY_UPDATES"
echo "  HR.HRAPP_COMPENSATION_SUMMARY"
echo "  HRAPP_COMPENSATION_ANALYST"
echo "  WEB_HR_APP application identity"
echo "  WEB_HR_APP_USER"
echo "Missing objects are skipped."
echo

sqlplus -s / as sysdba <<EOF
set echo off
set serveroutput on
whenever sqlerror exit sql.sqlcode

ALTER SESSION SET CONTAINER = ${PDB_NAME};

prompt Dropping Web HR App lab objects if they exist.

BEGIN
  BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY web_hr_app_employee_audit'; DBMS_OUTPUT.PUT_LINE('Disabled WEB_HR_APP_EMPLOYEE_AUDIT.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped disable WEB_HR_APP_EMPLOYEE_AUDIT.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY web_hr_app_employee_audit'; DBMS_OUTPUT.PUT_LINE('Dropped WEB_HR_APP_EMPLOYEE_AUDIT.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped drop WEB_HR_APP_EMPLOYEE_AUDIT.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sys.web_hr_disable_salary_updates'; DBMS_OUTPUT.PUT_LINE('Dropped SYS.WEB_HR_DISABLE_SALARY_UPDATES.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped SYS.WEB_HR_DISABLE_SALARY_UPDATES.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sys.web_hr_enable_salary_updates'; DBMS_OUTPUT.PUT_LINE('Dropped SYS.WEB_HR_ENABLE_SALARY_UPDATES.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped SYS.WEB_HR_ENABLE_SALARY_UPDATES.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP DATA GRANT hr.HRAPP_COMPENSATION_SUMMARY'; DBMS_OUTPUT.PUT_LINE('Dropped HR.HRAPP_COMPENSATION_SUMMARY.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped HR.HRAPP_COMPENSATION_SUMMARY.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP DATA ROLE HRAPP_COMPENSATION_ANALYST'; DBMS_OUTPUT.PUT_LINE('Dropped HRAPP_COMPENSATION_ANALYST.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped HRAPP_COMPENSATION_ANALYST.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP APPLICATION IDENTITY web_hr_app'; DBMS_OUTPUT.PUT_LINE('Dropped WEB_HR_APP application identity.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped WEB_HR_APP application identity.'); END;
  BEGIN EXECUTE IMMEDIATE 'DROP USER web_hr_app_user'; DBMS_OUTPUT.PUT_LINE('Dropped WEB_HR_APP_USER.'); EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skipped WEB_HR_APP_USER.'); END;
END;
/

exit;
EOF

echo "Web HR App database objects removed."
