spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=dbsec-lab.dbseclabs.com)(PORT=2484))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=pdb9)))
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Oracle wallet for TCPS
oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/u01/app/oracle/admin/cdb9/wallet)))
oracle.net.ssl_server_dn_match=false

server.port=8090
