spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=${ORACLE_HOST:localhost})(PORT=${ORACLE_PORT:1521}))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=${PDB_NAME:pdb1})))
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8090
